import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navigation
    home: 'Home',
    services: 'Services',
    about: 'About',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    
    // Home page
    welcome: 'Welcome to the Blue Book Renewal System',
    registerAndRenew: 'Register and renew your vehicle documents easily and securely.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    
    // Dashboard
    dashboard: 'Dashboard',
    profile: 'Profile',
    payment: 'Payment',
    newBluebook: 'New Bluebook',
    recentUsers: 'Recent Users',
    recentBluebooks: 'Recent Bluebooks',
    systemStats: 'System Statistics',
    welcomeBack: 'Welcome back',
    createNewBluebook: 'Create a new bluebook',
    makePayment: 'Make a payment',
    manageProfile: 'Manage your profile',
    help: 'Help',
    getSupport: 'Get support',
    recentActivity: 'Recent Activity',
    completed: 'Completed',
    failed: 'Failed',
    totalBluebooks: 'Total Bluebooks',
    verified: 'Verified',
    expired: 'Expired',
    myBluebooks: 'My Bluebooks',
    manageBluebooks: 'Manage your vehicle bluebook registrations',
    noBluebooks: 'No bluebooks',
    getStartedBluebook: 'Get started by creating a new bluebook registration.',
    regNo: 'Reg No',
    model: 'Model',
    number: 'Number',
    taxExpires: 'Tax Expires',
    created: 'Created',
    download: 'Download',
    payTax: 'Pay Tax',
    quickActions: 'Quick Actions',
    commonTasks: 'Common tasks and shortcuts',
    registerNewBluebook: 'Register New Bluebook',
    viewProfile: 'View Profile',
    
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    totalUsers: 'Total Users',
    totalBluebooks: 'Total Bluebooks',
    pendingApprovals: 'Pending Approvals',
    systemOverview: 'System Overview',
    userManagement: 'User Management',
    bluebookManagement: 'Bluebook Management',
    approve: 'Approve',
    reject: 'Reject',
    more: 'More',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    user: 'User',
    vehicle: 'Vehicle',
    owner: 'Owner',
    
    // Bluebook Detail
    bluebookDetail: 'Bluebook Detail',
    vehicleInformation: 'Vehicle Information',
    ownerInformation: 'Owner Information',
    registrationDetails: 'Registration Details',
    taxInformation: 'Tax Information',
    vehicleType: 'Vehicle Type',
    vehicleNumber: 'Vehicle Number',
    vehicleModel: 'Vehicle Model',
    vehicleRegNo: 'Registration Number',
    vehicleOwnerName: 'Owner Name',
    vehicleOwnerAddress: 'Owner Address',
    vehicleOwnerPhone: 'Owner Phone',
    vehicleOwnerEmail: 'Owner Email',
    registrationDate: 'Registration Date',
    expiryDate: 'Expiry Date',
    taxAmount: 'Tax Amount',
    taxStatus: 'Tax Status',
    valid: 'Valid',
    invalid: 'Invalid',
    
    // Forgot Password
    forgotPassword: 'Forgot Password',
    resetPassword: 'Reset Password',
    enterEmailForReset: 'Enter your email address to reset your password',
    sendResetLink: 'Send Reset Link',
    resetLinkSent: 'Reset link sent to your email',
    backToLogin: 'Back to Login',
    
    // OTP and Reset Password
    enterOtp: 'Enter OTP',
    otpSent: 'OTP sent to your email',
    verifyOtp: 'Verify OTP',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    resetPasswordSuccess: 'Password reset successfully',
    resendOtp: 'Resend OTP',
    otpExpiresIn: 'OTP expires in',
    
    // New Bluebook
    createBluebook: 'Create New Bluebook',
    bluebookForm: 'Bluebook Registration Form',
    personalInformation: 'Personal Information',
    vehicleDetails: 'Vehicle Details',
    uploadDocuments: 'Upload Documents',
    submitApplication: 'Submit Application',
    citizenshipNumber: 'Citizenship Number',
    address: 'Address',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    vehicleMake: 'Vehicle Make',
    vehicleYear: 'Vehicle Year',
    engineNumber: 'Engine Number',
    chassisNumber: 'Chassis Number',
    uploadPhoto: 'Upload Photo',
    uploadDocuments: 'Upload Documents',
    termsAndConditions: 'Terms and Conditions',
    agreeToTerms: 'I agree to the terms and conditions',
    selectVehicleType: 'Select vehicle type',
    vehicleRegistrationNumber: 'Vehicle Registration Number',
    enterRegistrationNumber: 'Enter registration number',
    vehicleRegistrationDate: 'Vehicle Registration Date',
    enterOwnerName: 'Enter owner name',
    enterVehicleModel: 'e.g., Honda City, Toyota Corolla',
    manufactureYear: 'Manufacture Year',
    enterManufactureYear: 'e.g., 2020',
    chasisNumber: 'Chassis Number',
    vehicleColor: 'Vehicle Color',
    selectColor: 'Select color',
    vehicleEngineCC: 'Engine CC',
    enterEngineCC: 'e.g., 1500',
    enterVehicleNumber: 'e.g., Ba 1 Pa 1234',
    taxPayDate: 'Tax Pay Date',
    taxExpireDate: 'Tax Expire Date',
    registering: 'Registering...',
    registerBluebook: 'Register Bluebook',
    
    // Payment
    paymentDetails: 'Payment Details',
    paymentAmount: 'Payment Amount',
    paymentMethod: 'Payment Method',
    khalti: 'Khalti',
    esewa: 'eSewa',
    bankTransfer: 'Bank Transfer',
    cardPayment: 'Card Payment',
    proceedToPayment: 'Proceed to Payment',
    paymentSuccessful: 'Payment Successful',
    paymentFailed: 'Payment Failed',
    transactionId: 'Transaction ID',
    paymentDate: 'Payment Date',
    paymentStatus: 'Payment Status',
    vehicleTaxPayment: 'Vehicle Tax Payment',
    payVehicleTaxOnline: 'Pay your vehicle tax online, securely and easily.',
    registrationNumber: 'Registration Number',
    engineCC: 'Engine CC',
    taxCalculation: 'Tax Calculation',
    baseTax: 'Base Tax',
    renewalCharge: 'Renewal Charge',
    fineAmount: 'Fine Amount',
    oldVehicleTax: 'Old Vehicle Tax (10%)',
    totalAmount: 'Total Amount',
    pay: 'Pay',
    taxPaymentNotDue: 'Tax payment is not due yet. You can pay when there are less than 30 days remaining.',
    enterOTP: 'Enter OTP',
    pleaseCheckEmailForOTP: 'Please check your email for the OTP and enter it below to confirm your payment.',
    enter6DigitOTP: 'Enter 6-digit OTP',
    verifyOTP: 'Verify OTP',
    didNotReceiveOTP: "Didn't receive OTP? Check your email or try again.",
    completePayment: 'Complete Payment',
    yourPaymentConfirmed: 'Your payment has been confirmed. You will be redirected to Khalti to complete your payment securely.',
    afterPaymentVerifyTransaction: 'After payment, you can verify your transaction using the transaction ID.',
    
    // Payment Verification
    paymentVerification: 'Payment Verification',
    verifyingPayment: 'Verifying Payment',
    paymentVerified: 'Payment Verified',
    paymentPending: 'Payment Pending',
    paymentRejected: 'Payment Rejected',
    pleaseWait: 'Please wait...',
    backToDashboard: 'Back to Dashboard',
    makeAnotherPayment: 'Make Another Payment',
    
    // Profile
    profileInformation: 'Profile Information',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    profileUpdated: 'Profile Updated Successfully',
    passwordChanged: 'Password Changed Successfully',
    
    // Common Actions
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    update: 'Update',
    create: 'Create',
    remove: 'Remove',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    
    // Messages
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    confirmation: 'Confirmation',
    areYouSure: 'Are you sure?',
    thisActionCannotBeUndone: 'This action cannot be undone.',
    
    // Placeholders
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    enterName: 'Enter your name',
    enterPhone: 'Enter your phone number',
    enterAddress: 'Enter your address',
    enterCitizenshipNumber: 'Enter your citizenship number',
    enterVehicleNumber: 'Enter vehicle number',
    enterEngineNumber: 'Enter engine number',
    enterChassisNumber: 'Enter chassis number',
    
    // Forms
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone Number',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    
    // Status
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    active: 'Active',
    inactive: 'Inactive',
    
    // Login specific
    enterCredentials: 'Enter your credentials to login',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    
    // Register specific
    createAccount: 'Create your account',
    haveAccount: 'Already have an account?',
    
    // Government Header
    governmentOfNepal: 'Government of Nepal',
    ministryOfPhysicalInfrastructure: 'Ministry of Physical Infrastructure and Transport',
    departmentOfTransportManagement: 'Department of Transport Management',
    nepal: 'Nepal',
    
    // Date Format
    dateFormat: 'MMMM DD, YYYY',
    timeFormat: 'HH:mm:ss',
  },
  ne: {
    // Navigation
    home: 'गृह',
    services: 'सेवाहरू',
    about: 'हाम्रो बारेमा',
    contact: 'सम्पर्क',
    login: 'लग - इन',
    register: 'दर्ता गर्नुहोस्',
    logout: 'लगआउट',
    
    // Home page
    welcome: 'ब्लू बुक नविकरण प्रणालीमा स्वागत छ',
    registerAndRenew: 'आफ्नो सवारी साधनका कागजातहरू सजिलै र सुरक्षित रूपमा दर्ता र नविकरण गर्नुहोस्।',
    getStarted: 'सुरु गर्नुहोस्',
    learnMore: 'थप जानकारी',
    
    // Dashboard
    dashboard: 'ड्यासबोर्ड',
    profile: 'प्रोफाइल',
    payment: 'भुक्तानी',
    newBluebook: 'नयाँ ब्लूबुक',
    recentUsers: 'हालका प्रयोगकर्ताहरू',
    recentBluebooks: 'हालका ब्लूबुकहरू',
    systemStats: 'प्रणाली तथ्यांक',
    welcomeBack: 'वर्तमान प्रवेश',
    createNewBluebook: 'नयाँ ब्लूबुक सिर्जना गर्नुहोस्',
    makePayment: 'भुक्तानी गर्नुहोस्',
    manageProfile: 'आफ्नो प्रोफाइल प्रबंधन गर्नुहोस्',
    help: 'मद्दत',
    getSupport: 'मद्दत हरू प्राप्त गर्नुहोस्',
    recentActivity: 'हालका क्रिया',
    completed: 'पूरा गरिएको',
    failed: 'असफल',
    totalBluebooks: 'कुल ब्लूबुकहरू',
    verified: 'सत्यापित',
    expired: 'समाप्त',
    myBluebooks: 'मेरो ब्लूबुकहरू',
    manageBluebooks: 'आफ्नो सवारी साधनका ब्लूबुक प्राविष्टनहरू प्रबंधन गर्नुहोस्',
    noBluebooks: 'कुनै ब्लूबुक छैन',
    getStartedBluebook: 'नयाँ ब्लूबुक प्राविष्टन सिर्जना गर्न आफ्नो सुरु गर्नुहोस्।',
    regNo: 'प्रमाण नं',
    model: 'मोडल',
    number: 'नम्बर',
    taxExpires: 'कर समाप्त',
    created: 'सिर्जना गरिएको',
    download: 'डाउनलोड',
    payTax: 'कर भुक्तानी',
    quickActions: 'झुक्को कार्यहरू र छोटो अन्तर्गत',
    commonTasks: 'सामान्य कार्य र छोटो अन्तर्गत',
    registerNewBluebook: 'नयाँ ब्लूबुक प्राविष्टन दर्ता गर्नुहोस्',
    viewProfile: 'प्रोफाइल हेर्नुहोस्',
    
    // Admin Dashboard
    adminDashboard: 'व्यवस्थापक ड्यासबोर्ड',
    totalUsers: 'कुल प्रयोगकर्ताहरू',
    totalBluebooks: 'कुल ब्लूबुकहरू',
    pendingApprovals: 'अनुमोदन अनुरोध',
    systemOverview: 'प्रणाली सारांश',
    userManagement: 'प्रयोगकर्ता व्यवस्था',
    bluebookManagement: 'ब्लूबुक व्यवस्था',
    approve: 'अनुमोदन गर्नुहोस्',
    reject: 'अस्वीकृत गर्नुहोस्',
    more: 'थप',
    actions: 'कार्यहरू',
    status: 'स्थिति',
    date: 'तारीख',
    user: 'प्रयोगकर्ता',
    vehicle: 'सवारी साधन',
    owner: 'स्वामी',
    
    // Bluebook Detail
    bluebookDetail: 'ब्लूबुक विवरण',
    vehicleInformation: 'सवारी साधनका विवरण',
    ownerInformation: 'स्वामीका विवरण',
    registrationDetails: 'प्रमाणन विवरण',
    taxInformation: 'कर विवरण',
    vehicleType: 'सवारी साधनको प्रकार',
    vehicleNumber: 'सवारी साधनको नम्बर',
    vehicleModel: 'सवारी साधनको मोडल',
    vehicleRegNo: 'प्रमाण नं',
    vehicleOwnerName: 'स्वामीको नाम',
    vehicleOwnerAddress: 'स्वामीको ठेगाना',
    vehicleOwnerPhone: 'स्वामीको फोन नम्बर',
    vehicleOwnerEmail: 'स्वामीको इमेल',
    registrationDate: 'प्रमाणन तारीख',
    expiryDate: 'समाप्ति तारीख',
    taxAmount: 'कर रकम',
    taxStatus: 'करको स्थिति',
    valid: 'वैध',
    invalid: 'अवैध',
    
    // Forgot Password
    forgotPassword: 'पासवर्ड भूल्नुभएको?',
    resetPassword: 'पासवर्ड सुरुकोटा',
    enterEmailForReset: 'तपाईंको पासवर्ड सुरुकोटा गर्न आफ्नो इमेल प्रविष्ट गर्नुहोस्',
    sendResetLink: 'पासवर्ड सुरुकोटा दिनुहोस्',
    resetLinkSent: 'तपाईंको इमेलमा पासवर्ड सुरुकोटा दिइएको छ।',
    backToLogin: 'लग - इनमा फिर्ता',
    
    // OTP and Reset Password
    enterOtp: 'OTP प्रविष्ट गर्नुहोस्',
    otpSent: 'तपाईंको इमेलमा OTP दिइएको छ।',
    verifyOtp: 'OTP पुष्टि गर्नुहोस्',
    newPassword: 'नयाँ पासवर्ड',
    confirmNewPassword: 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
    resetPasswordSuccess: 'पासवर्ड सुरुकोटा सफलतापूर्वक गरिएको छ।',
    resendOtp: 'OTP पुनरावर्तन गर्नुहोस्',
    otpExpiresIn: 'OTP अन्तर्गत समाप्त हुन्छ',
    
    // New Bluebook
    createBluebook: 'नयाँ ब्लूबुक सिर्जना गर्नुहोस्',
    bluebookForm: 'ब्लूबुक प्रमाणन प्रविष्टन फार्म',
    personalInformation: 'व्यक्तिगत विवरण',
    vehicleDetails: 'सवारी साधनका विवरण',
    uploadDocuments: 'कागजातहरू अपलोड गर्नुहोस्',
    submitApplication: 'अनुप्रयोग पेश गर्नुहोस्',
    citizenshipNumber: 'नागरिकता नं',
    address: 'ठेगाना',
    phoneNumber: 'फोन नम्बर',
    emailAddress: 'इमेल ठेगाना',
    vehicleMake: 'सवारी साधनको नाम',
    vehicleYear: 'सवारी साधनको वर्ष',
    engineNumber: 'इंजिन नं',
    chassisNumber: 'चासिस नं',
    uploadPhoto: 'फोटो अपलोड गर्नुहोस्',
    uploadDocuments: 'कागजातहरू अपलोड गर्नुहोस्',
    termsAndConditions: 'शर्तहरू र शर्तहरू',
    agreeToTerms: 'म शर्तहरू र शर्तहरू सहमत छु।',
    selectVehicleType: 'सवारी साधनको प्रकार चयन गर्नुहोस्',
    vehicleRegistrationNumber: 'सवारी साधनको प्रमाण नं',
    enterRegistrationNumber: 'प्रमाण नं प्रविष्ट गर्नुहोस्',
    vehicleRegistrationDate: 'सवारी साधनको प्रमाणन तारीख',
    enterOwnerName: 'स्वामीको नाम प्रविष्ट गर्नुहोस्',
    enterVehicleModel: 'उदाहरणको लागि, होडा सिटी, टोयोटा कोरोला',
    manufactureYear: 'बनाउने वर्ष',
    enterManufactureYear: 'उदाहरणको लागि, 2020',
    chasisNumber: 'चासिस नं',
    vehicleColor: 'सवारी साधनको रंग',
    selectColor: 'रंग चयन गर्नुहोस्',
    vehicleEngineCC: 'इंजिन CC',
    enterEngineCC: 'उदाहरणको लागि, 1500',
    enterVehicleNumber: 'उदाहरणको लागि, बा १ पा १२३४',
    taxPayDate: 'कर भुक्तानी तारीख',
    taxExpireDate: 'कर समाप्ति तारीख',
    registering: 'प्रमाणन गर्दै...',
    registerBluebook: 'ब्लूबुक प्रमाणन दर्ता गर्नुहोस्',
    
    // Payment
    paymentDetails: 'भुक्तानी विवरण',
    paymentAmount: 'भुक्तानी रकम',
    paymentMethod: 'भुक्तानी विधि',
    khalti: 'खल्ती',
    esewa: 'ईसेवा',
    bankTransfer: 'बैंक स्थानान्तरण',
    cardPayment: 'कार्ड भुक्तानी',
    proceedToPayment: 'भुक्तानीमा जानुहोस्',
    paymentSuccessful: 'भुक्तानी सफल',
    paymentFailed: 'भुक्तानी असफल',
    transactionId: 'लेखा नं',
    paymentDate: 'भुक्तानी तारीख',
    paymentStatus: 'भुक्तानी स्थिति',
    vehicleTaxPayment: 'सवारी साधनको कर भुक्तानी',
    payVehicleTaxOnline: 'आफ्नो सवारी साधनको कर अनलाइन, सुरक्षित र सजिलै भुक्तानी गर्नुहोस्।',
    registrationNumber: 'प्रमाण नं',
    engineCC: 'इंजिन CC',
    taxCalculation: 'कर गणना',
    baseTax: 'आधार कर',
    renewalCharge: 'नवीनीकरण शुल्क',
    fineAmount: 'जरिवाना रकम',
    oldVehicleTax: 'पुरानो सवारी साधनको कर (10%)',
    totalAmount: 'कुल रकम',
    pay: 'भुक्तानी गर्नुहोस्',
    taxPaymentNotDue: 'कर भुक्तानी अहिले समयमा छैन। 30 दिन भन्दा कम बाँकी हुँदा तपाईं भुक्तानी गर्न सक्नुहुन्छ।',
    enterOTP: 'OTP प्रविष्ट गर्नुहोस्',
    pleaseCheckEmailForOTP: 'कृपया आफ्नो इमेलमा OTP जाँच गर्नुहोस् र आफ्नो भुक्तानी पुष्टि गर्न तल प्रविष्ट गर्नुहोस्।',
    enter6DigitOTP: '6 अंकको OTP प्रविष्ट गर्नुहोस्',
    verifyOTP: 'OTP पुष्टि गर्नुहोस्',
    didNotReceiveOTP: 'OTP प्राप्त भएन? आफ्नो इमेल जाँच गर्नुहोस् वा फेरि प्रयास गर्नुहोस्।',
    completePayment: 'भुक्तानी पूरा गर्नुहोस्',
    yourPaymentConfirmed: 'तपाईंको भुक्तानी पुष्टि गरिएको छ। तपाईंलाई सुरक्षित भुक्तानी पूरा गर्न खल्तीमा पुनर्निर्देशन गरिनेछ।',
    afterPaymentVerifyTransaction: 'भुक्तानी पछि, तपाईंले लेखा नं प्रयोग गरेर आफ्नो लेनदेन पुष्टि गर्न सक्नुहुन्छ।',
    
    // Payment Verification
    paymentVerification: 'भुक्तानी पुष्टि',
    verifyingPayment: 'भुक्तानी पुष्टि गर्नुहोस्',
    paymentVerified: 'भुक्तानी पुष्टि गरिएको',
    paymentPending: 'भुक्तानी प्रक्रियामा',
    paymentRejected: 'भुक्तानी अस्वीकृत',
    pleaseWait: 'कृपया प्रतीक्षा गर्नुहोस्...',
    backToDashboard: 'ड्यासबोर्डमा फिर्ता',
    makeAnotherPayment: 'अर्को भुक्तानी गर्नुहोस्',
    
    // Profile
    profileInformation: 'प्रोफाइल विवरण',
    editProfile: 'प्रोफाइल सम्पादन गर्नुहोस्',
    saveChanges: 'परिवर्तनहरू सुरक्षित गर्नुहोस्',
    changePassword: 'पासवर्ड परिवर्तन गर्नुहोस्',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नयाँ पासवर्ड',
    confirmPassword: 'नयाँ पासवर्ड पुष्टि गर्नुहोस्',
    profileUpdated: 'प्रोफाइल सफलतापूर्वक सुरक्षित गरिएको छ।',
    passwordChanged: 'पासवर्ड सफलतापूर्वक परिवर्तित गरिएको छ।',
    
    // Common Actions
    edit: 'सम्पादन गर्नुहोस्',
    delete: 'मेटाउनुहोस्',
    view: 'हेर्नुहोस्',
    save: 'सुरक्षित गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    submit: 'पेश गर्नुहोस्',
    update: 'अपडेट गर्नुहोस्',
    create: 'सिर्जना गर्नुहोस्',
    remove: 'हटाउनुहोस्',
    close: 'बन्द गर्नुहोस्',
    back: 'फिर्ता',
    next: 'अर्को',
    previous: 'अघिल्लो',
    yes: 'हो',
    no: 'होइन',
    ok: 'ठिक छ',
    
    // Messages
    loading: 'लोड हुँदैछ...',
    error: 'त्रुटि',
    success: 'सफल',
    warning: 'चेतावनी',
    info: 'जानकारी',
    confirmation: 'पुष्टि',
    areYouSure: 'के तपाईं सुन्दर छ?',
    thisActionCannotBeUndone: 'यो कार्य अहिलेको हुन्छ।',
    
    // Placeholders
    enterEmail: 'आफ्नो इमेल प्रविष्ट गर्नुहोस्',
    enterPassword: 'आफ्नो पासवर्ड प्रविष्ट गर्नुहोस्',
    enterName: 'आफ्नो नाम प्रविष्ट गर्नुहोस्',
    enterPhone: 'आफ्नो फोन नम्बर प्रविष्ट गर्नुहोस्',
    enterAddress: 'आफ्नो ठेगाना प्रविष्ट गर्नुहोस्',
    enterCitizenshipNumber: 'आफ्नो नागरिकता नं प्रविष्ट गर्नुहोस्',
    enterVehicleNumber: 'सवारी साधनको नम्बर प्रविष्ट गर्नुहोस्',
    enterEngineNumber: 'इंजिन नं प्रविष्ट गर्नुहोस्',
    enterChassisNumber: 'चासिस नं प्रविष्ट गर्नुहोस्',
    
    // Forms
    email: 'इमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड पुष्टि गर्नुहोस्',
    firstName: 'पहिलो नाम',
    lastName: 'अन्तिम नाम',
    phone: 'फोन नम्बर',
    submit: 'पेश गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    save: 'सुरक्षित गर्नुहोस्',
    edit: 'सम्पादन गर्नुहोस्',
    delete: 'मेटाउनुहोस्',
    
    // Status
    pending: 'प्रक्रियामा',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    
    // Login specific
    enterCredentials: 'लग - इन गर्न आफ्नो क्रेडेंशियलहरू प्रविष्ट गर्नुहोस्',
    forgotPassword: 'पासवर्ड भूल्नुभएको?',
    noAccount: 'खाता छैन?',
    
    // Register specific
    createAccount: 'आफ्नो खाता गर्नुहोस्',
    haveAccount: 'केहि खाता छ?',
    
    // Government Header
    governmentOfNepal: 'नेपाल सरकार',
    ministryOfPhysicalInfrastructure: 'भौतिक पूर्वाधार तथा यातायात मन्त्रालय',
    departmentOfTransportManagement: 'यातायात व्यवस्था विभाग',
    nepal: 'नेपाल',
    
    // Date Format
    dateFormat: 'MMMM DD, YYYY',
    timeFormat: 'HH:mm:ss',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const toggleLanguage = () => setLanguage((prev) => (prev === 'en' ? 'ne' : 'en'));
  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext); 